assert(SMODS.load_file("src/Atlases.lua"))()
assert(SMODS.load_file("src/Extras.lua"))()
assert(SMODS.load_file("src/Tarots.lua"))()
assert(SMODS.load_file("src/Spectrals.lua"))()
assert(SMODS.load_file("src/Uncommons.lua"))()
assert(SMODS.load_file("src/Rares.lua"))()
assert(SMODS.load_file("src/Ghosts.lua"))()
